name: check_syntax

on:
  push:
    branches:
      - main  #uruchomienie tylko po push na main

jobs:
  check_syntax:
    runs-on: ubuntu-latest

    strategy: #uruchomienie testów dla różnych wersji Pythona 
      matrix:
        python-version: [3.9, '3.10', '3.11']

    steps:
      - name: Set up Python  #konfiguracja środowiska Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Update pip  #aktualizacja pip
        run: |
          python -m pip install --upgrade pip

      - name: Install flake8  #instalacja flake8
        run: |
          python -m pip install flake8

      - name: Display Python version  #wyświetlenie wersji pythona
        run: |
          python --version

      - name: Run flake8  #uruchomienie flake8
        run: |
          flake8 .
